development:
  adapter: postgresql
  encoding: unicode
  database: fuzion_development
  pool: 5
  username: laurent
  password: laurent

test:
  adapter: postgresql
  encoding: unicode
  database: fuzion_test
  pool: 5
  username: laurent
  password: laurent

production:
  adapter: postgresql
  encoding: unicode
  database: fuzion_production
  pool: 5
  username: rails
  password: laurent 
  host: laurent
